# Generated by Django 5.1.1 on 2024-11-09 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeer',
            name='email',
        ),
        migrations.RemoveField(
            model_name='jobseeker',
            name='email',
        ),
        migrations.AlterField(
            model_name='employeer',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
