# Generated by Django 5.1.1 on 2024-11-09 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_jobpost_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobpost',
            old_name='Employer',
            new_name='user',
        ),
    ]
