# Generated by Django 5.1.1 on 2024-11-12 15:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_jobpost_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='posted_at',
            field=models.DateField(default=datetime.datetime(2024, 11, 9, 0, 0)),
            preserve_default=False,
        ),
    ]
